services:
  postgres:
    image: postgres:18.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: olongapunta_db
    ports:
      - "5436:5432"
    volumes:
      - postgres:/var/lib/postgresql

volumes:
  postgres:
